package paint.ControlElements;

public enum InputHandlingStates {
    GOOD,
    BAD,
    QUIT,
    NO_FILE,
    NOT_EXISTING_COMMAND,
    EMPTY_COMMAND,
    TO_FEW_ARGUMENTS_FOR_ADD,
    NON_EXISTING_FIGURE,
    TO_FEW_ARGUMENTS_FOR_DELETE,
    TO_FEW_ARGUMENTS_FOR_FILL,
    TO_FEW_ARGUMENTS_FOR_MOVE,
    TO_FEW_ARGUMENTS_FOR_SAVE,
    TO_FEW_ARGUMENTS_FOR_LOAD,
    INVALID_COLOR,
    INVALID_NUMBER,
    INVALID_INDEX,
    BAD_FIGURE_PARAMETRS
}
